added Git commit of release build

diff --git a/.github/workflows/maven-release.yml b/.github/workflows/maven-release.yml
--- a/.github/workflows/maven-release.yml
+++ b/.github/workflows/maven-release.yml
@@ -115,7 +115,7 @@ jobs:
                                    -s ../../ci_settings.xml \
                                    -DskipTests \
                                    -DfullBuild
-            -   name:  Upload artifacts to GitHub Release
+            -   name:              Upload artifacts to GitHub Release
                 working-directory: target/checkout
                 env:
                     GITHUB_TOKEN:             ${{ secrets.GITHUB_TOKEN }}
@@ -127,67 +127,67 @@ jobs:
                     mvnsiteuploader_password: ${{ secrets.MVNSITEUPLOADER_PASSWORD }}
                     mvn_central_user:         ${{ secrets.MVN_CENTRAL_USER }}
                     mvn_central_token:        ${{ secrets.MVN_CENTRAL_TOKEN }}
-                shell: bash
-                run:   |
-                       set -euo pipefail
-                       set -x
+                shell:             bash
+                run:               |
+                                   set -euo pipefail
+                                   set -x
 
-                       TAG="${{ steps.get_tag.outputs.tag_name }}"
-                       echo "Upload to GitHub release: $TAG"
+                                   TAG="${{ steps.get_tag.outputs.tag_name }}"
+                                   echo "Upload to GitHub release: $TAG"
 
-                       SETTINGS_FILE="../../ci_settings.xml"
+                                   SETTINGS_FILE="../../ci_settings.xml"
 
-                       echo "::group::Prepare modules list"
-                       ROOT_BUILD_DIR=$(mvn -B initialize help:evaluate -e -s $SETTINGS_FILE -Dexpression="project.build.directory" -Ddistribution -q -DforceStdout)
-                       MODULES_LIST_FILENAME="modules-list.txt"
-                       MODULES_LIST="$ROOT_BUILD_DIR/$MODULES_LIST_FILENAME"
+                                   echo "::group::Prepare modules list"
+                                   ROOT_BUILD_DIR=$(mvn -B initialize help:evaluate -e -s $SETTINGS_FILE -Dexpression="project.build.directory" -Ddistribution -q -DforceStdout)
+                                   MODULES_LIST_FILENAME="modules-list.txt"
+                                   MODULES_LIST="$ROOT_BUILD_DIR/$MODULES_LIST_FILENAME"
 
-                       MODULES=( "__ROOT__" )
-                       if [[ -f "$MODULES_LIST" ]]; then
-                         echo "Reading modules from: $MODULES_LIST"
-                         while IFS= read -r MODULE || [[ -n "$MODULE" ]]; do
-                           MODULES+=("$MODULE")
-                         done < "$MODULES_LIST"
-                       else
-                            echo "No modules list found at: $MODULES_LIST"
-                            echo "Using only default module: __ROOT__"
-                       fi
-                       echo "::endgroup::"
+                                   MODULES=( "__ROOT__" )
+                                   if [[ -f "$MODULES_LIST" ]]; then
+                                     echo "Reading modules from: $MODULES_LIST"
+                                     while IFS= read -r MODULE || [[ -n "$MODULE" ]]; do
+                                       MODULES+=("$MODULE")
+                                     done < "$MODULES_LIST"
+                                   else
+                                        echo "No modules list found at: $MODULES_LIST"
+                                        echo "Using only default module: __ROOT__"
+                                   fi
+                                   echo "::endgroup::"
 
-                       for MODULE in "${MODULES[@]}"; do
-                         [[ -z "${MODULE//[$'\t\r\n ']/}" ]] && continue
-                         [[ "${MODULE:0:1}" == "#" ]] && continue
+                                   for MODULE in "${MODULES[@]}"; do
+                                     [[ -z "${MODULE//[$'\t\r\n ']/}" ]] && continue
+                                     [[ "${MODULE:0:1}" == "#" ]] && continue
 
-                         echo "::group::Module: $MODULE"
+                                     echo "::group::Module: $MODULE"
 
-                         if [[ "${MODULE}" == "__ROOT__" ]]; then
-                           MODULE=""
-                         fi
+                                     if [[ "${MODULE}" == "__ROOT__" ]]; then
+                                       MODULE=""
+                                     fi
 
-                         BUILD_DIR=$(mvn -B initialize help:evaluate -e -s $SETTINGS_FILE -Dexpression="project.build.directory" -Ddistribution -q -DforceStdout -pl "$MODULE")
-                         FILENAME=$(mvn -B initialize help:evaluate -e -s $SETTINGS_FILE -Dexpression="project.build.artifact.fileName" -Ddistribution -q -DforceStdout -pl "$MODULE")
-                         FINAL_NAME=$(mvn -B initialize help:evaluate -e -s $SETTINGS_FILE -Dexpression="project.build.finalName" -Ddistribution -q -DforceStdout -pl "$MODULE")
+                                     BUILD_DIR=$(mvn -B initialize help:evaluate -e -s $SETTINGS_FILE -Dexpression="project.build.directory" -Ddistribution -q -DforceStdout -pl "$MODULE")
+                                     FILENAME=$(mvn -B initialize help:evaluate -e -s $SETTINGS_FILE -Dexpression="project.build.artifact.fileName" -Ddistribution -q -DforceStdout -pl "$MODULE")
+                                     FINAL_NAME=$(mvn -B initialize help:evaluate -e -s $SETTINGS_FILE -Dexpression="project.build.finalName" -Ddistribution -q -DforceStdout -pl "$MODULE")
 
-                         ARTIFACT_PATH=${BUILD_DIR}/${FILENAME}
-                         echo "Uploading: $ARTIFACT_PATH"
-                         gh release upload "$TAG" "$ARTIFACT_PATH" --clobber || echo "Upload of $ARTIFACT_PATH failed!"
+                                     ARTIFACT_PATH=${BUILD_DIR}/${FILENAME}
+                                     echo "Uploading: $ARTIFACT_PATH"
+                                     gh release upload "$TAG" "$ARTIFACT_PATH" --clobber || echo "Upload of $ARTIFACT_PATH failed!"
 
-                         for CLASSIFIER in sources javadoc; do
-                           ARTIFACT_PATH="${BUILD_DIR}/${FINAL_NAME}-${CLASSIFIER}.jar"
-                           if [[ -f "$ARTIFACT_PATH" ]]; then
-                             echo "Uploading: $ARTIFACT_PATH"
-                             gh release upload "$TAG" "$ARTIFACT_PATH" --clobber || echo "Upload of $ARTIFACT_PATH failed!"
-                           fi
-                         done
+                                     for CLASSIFIER in sources javadoc; do
+                                       ARTIFACT_PATH="${BUILD_DIR}/${FINAL_NAME}-${CLASSIFIER}.jar"
+                                       if [[ -f "$ARTIFACT_PATH" ]]; then
+                                         echo "Uploading: $ARTIFACT_PATH"
+                                         gh release upload "$TAG" "$ARTIFACT_PATH" --clobber || echo "Upload of $ARTIFACT_PATH failed!"
+                                       fi
+                                     done
 
-                         echo "::endgroup::"
-                       done
+                                     echo "::endgroup::"
+                                   done
 
             -   name: Git Checkout Release Tag
                 uses: actions/checkout@v4
                 with:
-                  ref: '${{ steps.get_tag.outputs.tag_name }}'
-            -   name:  Build Release for Git Repository
+                    ref: '${{ steps.get_tag.outputs.tag_name }}'
+            -   name: Build Release for Git Repository
                 env:
                     GITHUB_TOKEN:             ${{ secrets.GITHUB_TOKEN }}
                     ci_git_user:              ${{ vars.CI_GIT_USER }}
@@ -204,3 +204,15 @@ jobs:
                       -e \
                       -s ci_settings.xml \
                       -DfullBuild -Ddistribution -Dexecutable
+            -   name: Commit & push changes
+                env:
+                    BRANCH: ${{ github.head_ref || github.ref_name }}
+                run:  |
+                      if git status --porcelain | grep .; then
+                        git add -A
+                        git commit -m "[Git Release Build] [skip ci] apply build updates"
+                        git pull --rebase origin "$BRANCH" || true
+                        git push origin HEAD:"$BRANCH"
+                      else
+                        echo "No changes to commit."
+                      fi
